--DROP TABLE USER IF EXISTS;
--DROP TABLE CITY IF EXISTS;
--DROP TABLE COUNTRY IF EXISTS;
--DROP TABLE CONTINENT IF EXISTS;

create table CONTINENT (
  ID    VARCHAR(10) PRIMARY KEY,
  CONTINENT_CODE VARCHAR(20),
  NAME  VARCHAR(50)
);

create table COUNTRY (
  ID    VARCHAR(10) PRIMARY KEY,
  COUNTRY_CODE VARCHAR(20),
  NAME  VARCHAR(50),
  CONTINENT_ID VARCHAR(10)
);

create table CITY (
  ID    VARCHAR(10) PRIMARY KEY,
  CITY_CODE VARCHAR(20),
  NAME  VARCHAR(50),
  COUNTRY_ID VARCHAR(10)
);

create table USER (
  ID    VARCHAR(10) PRIMARY KEY,
  NAME  VARCHAR(50),
  EMAIL_ADDRESS VARCHAR(50),
  CITY_ID VARCHAR(10)
);


