--DROP TABLE USER IF EXISTS;
--DROP TABLE CITY IF EXISTS;
--DROP TABLE COUNTRY IF EXISTS;

create table CONTINENT (
  ID    VARCHAR(10),
  UNIVERSE_ID VARCHAR(10),
  CONTINENT_CODE VARCHAR(20),
  NAME  VARCHAR(50),
  PRIMARY KEY (ID, UNIVERSE_ID)
);

create table COUNTRY (
  ID    VARCHAR(10),
  TYPE_ID VARCHAR(10),
  COUNTRY_CODE VARCHAR(20),
  NAME  VARCHAR(50),
  CONTINENT_ID VARCHAR(10),
  CONTINENT_UNIVERSE_ID VARCHAR(10),
  PRIMARY KEY (ID, TYPE_ID)
);

create table CITY (
  ID    VARCHAR(10),
  GROUP_ID VARCHAR(10),
  CITY_CODE VARCHAR(20),
  NAME  VARCHAR(50),
  COUNTRY_ID VARCHAR(10),
  COUNTRY_TYPE_ID VARCHAR(10),
  PRIMARY KEY (ID, GROUP_ID)
);
